<a href="https://colab.research.google.com/github/MIDSNCKRRR/rs/blob/main/Contents_Based.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 콘텐츠 기반 필터링 (Contents based filtering)

**굵은 텍스트**# 새 섹션

In [ ]:
# 사용자가 특정 아이템을 선호하는 경우, 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천해주는 방식
# 사용자가 a 영화에 높은 평점을 주었을때 그 영화의 특징을 기반으로 다른 영화를 추천함

#데이터 설명
#영화 출시 전 어떤 영화들이 좋은 평가 받을지 / 상업적인 성공을 거둘지 예측하기

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('./tmdb_5000_movies.csv')
df.head(10)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
5  258000000  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...   
6  260000000  [{"id": 16, "name": "Animation"}, {"id": 10751...   
7  280000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
8  250000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
9  250000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            homepage      id  \
0                        http://www.avatarmovie.com/   19995   
1       http://disney.go.com/disneypictures/pirates/     285   
2        http://www.sonypictures.com/movies/spectre/  206647   
3                 http://www.thedarkknightrises.com/   49026   
4               http://movies.disney.com/john-carter   49529   
5    http://www.sonypictures.com/movies/spider-man3/     559   
6       http://disney.go.com/disneypictures/tangled/   38757   
7  http://marvel.com/movies/movie/193/avengers_ag...   99861   
8  http://harrypotter.warnerbros.com/harrypottera...     767   
9       http://www.batmanvsupermandawnofjustice.com/  209112   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   
5  [{"id": 851, "name": "dual identity"}, {"id": ...                en   
6  [{"id": 1562, "name": "hostage"}, {"id": 2343,...                en   
7  [{"id": 8828, "name": "marvel comic"}, {"id": ...                en   
8  [{"id": 616, "name": "witch"}, {"id": 2343, "n...                en   
9  [{"id": 849, "name": "dc comics"}, {"id": 7002...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   
5                              Spider-Man 3   
6                                   Tangled   
7                   Avengers: Age of Ultron   
8    Harry Potter and the Half-Blood Prince   
9        Batman v Superman: Dawn of Justice   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   
5  The seemingly invincible Spider-Man goes up ag...  115.699814   
6  When the kingdom's most wanted-and most charmi...   48.681969   
7  When Tony Stark tries to jumpstart a dormant p...  134.279229   
8  As Harry begins his sixth year at Hogwarts, he...   98.885637   
9  Fearing the actions of a god-like Super Hero l...  155.790452   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   
5  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
6  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
7  [{"name": "Marvel Studios", "i

In [ ]:
#사용할 컬럼 정리
# (순서대로) 평점 평균, 평점 카운트, 인기도

In [ ]:
data = df[['id', 'genres', 'vote_average', 'vote_count', 'popularity', 'title', 'keywords', 
           'overview']]
data.head()

id                                             genres  vote_average  \
0   19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  206647  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3   49026  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4   49529  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   
2        4466  107.376788                                   Spectre   
3        9106  112.312950                     The Dark Knight Rises   
4        2124   43.926995                               John Carter   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [ ]:
#평점 전처리
m = data['vote_count'].quantile(0.9)
print(m)
data = data.loc[data['vote_count']>=m]

c = data['vote_average'].mean()

1838.4000000000015


In [ ]:
def weight_rating (x, m=m, c=c):
  v = x['vote_count']
  r = x ['vote_average']
  return (v / (v+m) *r ) + (m / (v+m) *c)

In [ ]:
data['score'] = data.apply(weight_rating, axis = 1)

In [ ]:
data.head()

id                                             genres  vote_average  \
0   19995  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     285  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  206647  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3   49026  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4   49529  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                     title  \
0       11800  150.437577                                    Avatar   
1        4500  139.082615  Pirates of the Caribbean: At World's End   
2        4466  107.376788                                   Spectre   
3        9106  112.312950                     The Dark Knight Rises   
4        2124   43.926995                               John Carter   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview     score  
0  In the 22nd century, a paraplegic Marine is di...  7.168053  
1  Captain Barbossa, long believed to be dead, ha...  6.918271  
2  A cryptic message from Bond’s past sends him o...  6.493333  
3  Following the death of District Attorney Harve...  7.492998  
4  John Carter is a war-weary, former military ca...  6.500396

In [ ]:
data.shape

(481, 9)

In [ ]:
# 콘텐츠 기반 필터링을 위한 컬럼 추출
# 비슷함의 기준을 장르와 키워드로 잡기.
# 장르와 키워드 값은 list 안에 dict 이 포함된 구조. string 으로 변환 필요
# ast 패키지의 literal_eval 로 변환시킨다

In [ ]:
data[['genres', 'keywords']].head()

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4  [{"id": 818, "name": "based on novel"}, {"id":...

In [ ]:
import ast as ast

In [ ]:
data['genres'] = data['genres'].apply(ast.literal_eval)
data['keywords'] = data['keywords'].apply(ast.literal_eval)

In [ ]:
data[['genres', 'keywords']].head()

genres  \
0  Action Adventure Fantasy Science Fiction   
1                  Adventure Fantasy Action   
2                    Action Adventure Crime   
3               Action Crime Drama Thriller   
4          Action Adventure Science Fiction   

                                            keywords  
0  culture clash future space war space colony so...  
1  ocean drug abuse exotic island east india trad...  
2  spy based on novel secret agent sequel mi6 bri...  
3  dc comics crime fighter terrorist secret ident...  
4  based on novel mars medallion space travel pri...

In [ ]:
data['genres'] = data['genres'].apply(lambda x :[d ['name'] for d in x]).apply(lambda x: " ".join(x))
data['keywords'] = data['keywords'].apply(lambda x :[d ['name'] for d in x]).apply(lambda x: " ".join(x))

In [ ]:
data['keywords'] = data['keywords'].apply(lambda x :[d ['name'] for d in x]).apply(lambda x: " ".join(x))

In [ ]:
# 콘텐츠 기반 필터링 추천
# 장르 벡터화
# 장르를 기준으로 필터링할 경우 -> 장르가 띄어쓰기가 구분된 한 문자열
# 문자열을 숫자로 바꿔 벡터화, CountVectorizer 사용

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
# CountVectorizer : 문서 집합에서 단어 토큰을 생성하고 각 단어의 수를 세어 BOW 인코딩 벡터를 만든다.

In [ ]:
counter_vector = CountVectorizer(ngram_range = (1,3))
c_vector_genres = counter_vector.fit_transform(data['genres'])

In [ ]:
c_vector_genres.shape

(481, 364)

In [ ]:

corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?',
]
vect = CountVectorizer(ngram_range=(1, 3)).fit(corpus)
vect.fit(corpus)
vect.vocabulary_

{'and': 0,
 'and the': 1,
 'and the third': 2,
 'document': 3,
 'first': 4,
 'first document': 5,
 'is': 6,
 'is the': 7,
 'is the first': 8,
 'is the second': 9,
 'is this': 10,
 'is this the': 11,
 'last': 12,
 'last document': 13,
 'one': 14,
 'second': 15,
 'second document': 16,
 'second second': 17,
 'second second document': 18,
 'the': 19,
 'the first': 20,
 'the first document': 21,
 'the last': 22,
 'the last document': 23,
 'the second': 24,
 'the second second': 25,
 'the third': 26,
 'the third one': 27,
 'third': 28,
 'third one': 29,
 'this': 30,
 'this is': 31,
 'this is the': 32,
 'this the': 33,
 'this the first': 34}

In [ ]:
# 유사도값 추출
from sklearn.metrics.pairwise import cosine_similarity
similarity_genre = cosine_similarity(c_vector_genres, c_vector_genres).argsort()[:, ::-1]
print(similarity_genre)

[[  0  13  42 ... 298 297 240]
 [ 11   1 200 ... 329 330 240]
 [  2 376 216 ... 314 304 240]
 ...
 [478 187  12 ... 326 327   0]
 [479 466 383 ... 220 224   0]
 [480 468 294 ... 246 248   0]]


In [ ]:
similarity_genre.shape
similarity_genre

array([[  0,  13,  42, ..., 298, 297, 240],
       [ 11,   1, 200, ..., 329, 330, 240],
       [  2, 376, 216, ..., 314, 304, 240],
       ...,
       [478, 187,  12, ..., 326, 327,   0],
       [479, 466, 383, ..., 220, 224,   0],
       [480, 468, 294, ..., 246, 248,   0]])

In [ ]:
# 장르기반의 유사도를 기준으로 영화를 추천해주는 사용자 함수
def rc_movie_list(df, movie_title, top = 30):
  #특정 영화정보 뽑아내기
  target_mv_index = df[df['title'] == movie_title].index.values
  #타겟영화와 비슷한 코사인 유사도값
  sim_index = similarity_genre[target_mv_index, : top].reshape(-1)
  #본인제외
  sim_index = sim_index[sim_index!= target_mv_index]
  #추천결과 새로운 DF 생성, 평균평점(score) 으로 정렬
  result = df.iloc[sim_index].sort_values('score', ascending = False)[:10]
  return result

In [ ]:
rc_movie_list(data, movie_title = 'Avatar')

id                                    genres  vote_average  \
85   100402          Action Adventure Science Fiction           7.6   
46   127585  Action Adventure Fantasy Science Fiction           7.5   
47    54138          Action Adventure Science Fiction           7.4   
19   122917                  Action Adventure Fantasy           7.1   
182  102899          Science Fiction Action Adventure           7.0   
426   70160         Science Fiction Adventure Fantasy           6.9   
126   76338                  Action Adventure Fantasy           6.8   
31    68721          Action Adventure Science Fiction           6.8   
507     602          Action Adventure Science Fiction           6.7   
30      558                  Action Adventure Fantasy           6.7   

     vote_count  popularity                                      title  \
85         5764   72.225265        Captain America: The Winter Soldier   
46         6032  118.078691                 X-Men: Days of Future Past   
47         4418   78.291018                    Star Trek Into Darkness   
19         4760  120.965743  The Hobbit: The Battle of the Five Armies   
182        5880  120.093610                                    Ant-Man   
426        9455   68.550698                           The Hunger Games   
126        4755   99.499595                       Thor: The Dark World   
31         8806   77.682080                                 Iron Man 3   
507        3260   60.442593                           Independence Day   
30         4321   35.149586                               Spider-Man 2   

                                              keywords  \
85   washington d.c. future shield marvel comic sup...   
46   1970s mutant time travel marvel comic based on...   
47   spacecraft friendship sequel futuristic space ...   
19   corruption elves dwarves orcs middle-earth (to...   
182  marvel comic superhero based on comic book aft...   
426  hallucination dystopia female protagonist bow ...   
126  marvel comic superhero based on comic book hos...   
31   terrorist war on terror tennessee malibu marve...   
507  spacecraft patriotism countdown independence i...   
30   dual identity love of one's life pizza boy mar...   

                                              overview     score  
85   After the cataclysmic events in New York with ...  7.445960  
46   The ultimate X-Men ensemble fights a war for t...  7.374564  
47   When the crew of the Enterprise is called back...  7.271589  
19   Immediately after the events of The Desolation...  7.061828  
182  Armed with the astonishing ability to shrink i...  6.991186  
426  Every year in the ruins of what was once North...  6.910254  
126  Thor fights to restore order across the cosmos...  6.845447  
31   When Tony Stark's world is torn apart by a for...  6.828151  
507  On July 2, a giant alien mothership enters orb...  6.794831  
30   Peter Parker is going through a major identity...  6.778496

In [ ]:
data

id                                    genres  vote_average  \
0      19995  Action Adventure Fantasy Science Fiction           7.2   
1        285                  Adventure Fantasy Action           6.9   
2     206647                    Action Adventure Crime           6.3   
3      49026               Action Crime Drama Thriller           7.6   
4      49529          Action Adventure Science Fiction           6.1   
...      ...                                       ...           ...   
4291     176                      Horror Mystery Crime           7.2   
4300     500                            Crime Thriller           8.0   
4302     429                                   Western           8.1   
4337     103                               Crime Drama           8.0   
4602     389                                     Drama           8.2   

      vote_count  popularity                                     title  \
0          11800  150.437577                                    Avatar   
1           4500  139.082615  Pirates of the Caribbean: At World's End   
2           4466  107.376788                                   Spectre   
3           9106  112.312950                     The Dark Knight Rises   
4           2124   43.926995                               John Carter   
...          ...         ...                                       ...   
4291        2184   63.655973                                       Saw   
4300        3697   66.925866                            Reservoir Dogs   
4302        2311   88.377076            The Good, the Bad and the Ugly   
4337        2535   58.845025                               Taxi Driver   
4602        2078   59.259204                              12 Angry Men   

                                               keywords  \
0     culture clash future space war space colony so...   
1     ocean drug abuse exotic island east india trad...   
2     spy based on novel secret agent sequel mi6 bri...   
3     dc comics crime fighter terrorist secret ident...   
4     based on novel mars medallion space travel pri...   
...                                                 ...   
4291  shotgun based on short film sadist pistol chai...   
4300  traitor jewelry psychopath thief heist betraya...   
4302  bounty hunter refugee gold anti hero gallows h...   
4337  vietnam veteran taxi obsession drug dealer nig...   
4602  judge jurors sultriness death penalty father m...   

                                               overview     score  
0     In the 22nd century, a paraplegic Marine is di...  7.168053  
1     Captain Barbossa, long believed to be dead, ha...  6.918271  
2     A cryptic message from Bond’s past sends him o...  6.493333  
3     Following the death of District Attorney Harve...  7.492998  
4     John Carter is a war-weary, former military ca...  6.500396  
...                                                 ...       ...  
4291  Obsessed with teaching his victims the value o...  7.091679  
4300  A botched robbery indicates a police informant...  7.655593  
4302  While the Civil War rages between the Union an...  7.596247  
4337  A mentally unstable Vietnam War veteran works ...  7.564085  
4602  The defense and the prosecution have rested an...  7.619336  

[481 rows x 9 columns]